#!/usr/bin/env bash

function message() {
	if [ $(echo $1 | awk '{ print length }') -eq 10 ]; then
		xdg-open "https://wa.me/+91$number"
		echo "Opening WhatsApp..."
	else
		echo "Error: Requires 10-digit number"
	fi
}

read -p "Phone Number: " number
message $number
